services:
  - type: web
    name: parkweb
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: "22"
